[package]
name = "folder-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
ftp = "3.0.1"
log = "0.4.26"
notify = "5.0"
simplelog = "0.12.2"
winapi = { version = "0.3", features = ["debugapi"] }
windows-service = "0.8.0"

[dev-dependencies]
tempfile = "3.17.1"
